### ISSUE TITLE
CIVET Recipes Not Public

### ISSUE THREAD

**Issue by pbauman** [idaholab/civet#174]
Trying to follow the link to the `civet_recipes` in the README gives me a 404; I'm guessing that the repo is not public yet. Any idea when it will be made public? Failing that, could an example of a recipe be added to the civet repo?

**Comment by brianmoose** [comment]
We are going to restructure the `civet_recipes` repo to allow for easier sharing. Apparently we can't open the actual recipes themselves but we can open the various scripts that are used by the recipes since they are pretty generic.
I will also add some sample recipes that demonstrate how basic tasks can be done.

**Comment by pbauman** [comment]
Cool, thanks. I know how I want to run all my tests (everything is captured in a `make check` target), I just need to know how CIVET will want to interact with that.

**Comment by brianmoose** [comment]
I created some sample recipes and scripts at https://github.com/idaholab/civet_example_recipes
Let me know if they make sense or if it confuses things even more :)

**Comment by pbauman** [comment]
Thanks! I'll close this out since there's access to recipes now.
