### ISSUE TITLE
Clarification on "Collaborator" for tests running in `authorized` mode

### ISSUE THREAD

**Issue by pbauman** [idaholab/civet#210]
I see in the recipe that we can set the `automatic` flag to `authorized` which will only run the tests if the user is a "collaborator". Is that a collaborator in the sense of GitHub? Or some other sense? e.g. I just added my PhD students as collaborators on the GitHub repo with only read access - will CIVET then run tests on PRs submitted by them? Thanks much.

**Comment by brianmoose** [comment]
Yes, it does an API check with GitHub to see if the user initiating the PR is a GitHub collaborator on the repository. If they are then the jobs are automatically set to be run (once dependencies are satisfied).
Otherwise they have to be manually activated by someone that is a collaborator on the repository.
So, your setup should do what you want. If it doesn't, please let me know and I will fix it.

**Comment by pbauman** [comment]
Sorry for not closing it out forever ago. Everything has been working as intended.
