### ISSUE TITLE
Have separate event list for PRs and devel

### ISSUE THREAD

**Issue by brianmoose** [idaholab/civet#359]
Currently the branch event list shows all events that are based on the branch. This means, for example, that showing events on the devel branch shows both PRs and tests on the devel branch.

It would be nice to separate the PR events into its own page and don't show PRs on the devel events.

**Comment by permcody** [comment]
Related to this ticket: It would be really nice if only merges on devel affected the status indicator that you see on mooseframework and github. This is probably the difference between seeing red (most of the time) and green.

**Comment by brianmoose** [comment]
So nightly tests don't affect the status? Do you want this optional per branch? So the nightly tests on master don't affect the master status?

**Comment by permcody** [comment]
Nightlies is technically a separate issue because they are **on** the branch instead of against it. I'd prefer to not have nightlies affect the status because we have several broken targets there but I could live with it if it was necessary. This ticket is specifically for PRs versus on the branch separation. 

Maybe I should just go skip or restrict the broken nightlies... hmm....

**Comment by brianmoose** [comment]
OK, PRs don't currently affect the devel branch status. There is already a check in there to not update the branch status on PRs but it will on everything else. It would be easy enough to ignore scheduled events as well. 
I can see it for the devel branch because we don't care too much about those tests but for the master branch it is a bit more important. For example, if valgrind heavy fails, that is a legitimate  problem on the master branch.
