### ISSUE TITLE
Minimum set of steps to run locally?

### ISSUE THREAD

**Issue by veeshy** [idaholab/civet#366]
I'd like to have a local machine be my CI for a private moose app, I don't quite see how to accomplish this. [Setting up git](https://github.com/idaholab/civet/wiki/Setting-up-a-GitHub-repository-to-be-tested) needs Payload URL: ABSOLUTE_BASE_URL/github/webhook/YOUR_BUILD_KEY/. What is my build_key (it says sign into civet, not sure what that means) and does needing an ABSOLUTE_BASE_URL mean I need to be hosting a webserver locally?

Thanks

**Comment by brianmoose** [comment]
That "Setting up git" wiki page assumes a running civet server. `ABSOLUTE_BASE_URL` is the URL to the civet server. GitHub needs to be able to connect to the civet server to inform it when events happen on repositories. 
On the civet server, you can log in by clicking on the "Sign in" next to the GitHub icon. Once signed in you can navigate to your username -> Civet Recipes and it will show your build key.

It might be overkill to set civet up if all you want is some simple testing. Depending on how private your code is, some of the free CI services might be viable (ie something like Travis CI).

Since it is a moose based code, you might be able to convince @permcody that it would be OK for us to host the testing results. Then you would just run a civet client on your local machine and it would report the results back to moosebuild.org. Running a civet client is much simpler than setting up a civet server.

**Comment by veeshy** [comment]
Ah, gotcha! Don't think I want to roll my own server. I went down the civet route since it was built with moose in mind. Think I'll try out travis CI to see if I can keep things private (ugh, legal!). Thanks for the quick reply!
